"""
Perform inference with pretrained SSL+HMM on CSV accelerometer files.
Requires a pretrained SSL and HMM (generated by train.py).

Arguments:
    Input CSV file path

Example usage:
    python inference_csv.py /path/to/FLAC_AG_LW_7111_7DRAW.csv

Output:
    Activity classifications CSV in specified format
"""

import argparse
import os
import torch
import pandas as pd
import numpy as np
import gzip

from pathlib import Path
from omegaconf import OmegaConf
from torch.utils.data import DataLoader
from utils.data import NormalDataset
from datetime import datetime

from models.hmm import HMM
import models.sslnet as ssl
import utils.utils as utils

DEVICE_HZ = 30  # Hz
WINDOW_SEC = 30  # seconds
WINDOW_OVERLAP_SEC = 0  # seconds
WINDOW_LEN = int(DEVICE_HZ * WINDOW_SEC)  # device ticks
WINDOW_OVERLAP_LEN = int(DEVICE_HZ * WINDOW_OVERLAP_SEC)  # device ticks
WINDOW_STEP_LEN = WINDOW_LEN - WINDOW_OVERLAP_LEN  # device ticks

log = utils.get_logger()
def read_csv_accelerometer(input_file):
    """Read ActiGraph CSV accelerometer data and prepare it like actipy output"""
    
    # Handle gzipped files
    if input_file.endswith('.gz'):
        with gzip.open(input_file, 'rt') as f:
            # Skip the header lines (first 10 lines) and read the data
            data = pd.read_csv(f, skiprows=10)
    else:
        # Skip the header lines (first 10 lines) and read the data
        data = pd.read_csv(input_file, skiprows=10)
    
    # Rename columns to standard format
    data = data.rename(columns={
        'Timestamp': 'timestamp',
        'Accelerometer X': 'x',
        'Accelerometer Y': 'y', 
        'Accelerometer Z': 'z'
    })
    
    # Parse timestamp and set as index
    data['timestamp'] = pd.to_datetime(data['timestamp'], format='%m/%d/%Y %H:%M:%S.%f')
    data.set_index('timestamp', inplace=True)
    
    # Keep only x, y, z columns
    data = data[['x', 'y', 'z']].copy()
    
    # Remove any NaN values
    data = data.dropna()
    
    # The original data is at 100Hz, but we need 30Hz for the model
    # Resample to 30Hz (every ~33.33ms)
    data = data.resample('33.33ms').mean()
    data = data.dropna()
    
    print(f"Original data points: {len(data)} at ~30Hz")
    print(f"Date range: {data.index[0]} to {data.index[-1]}")
    print(f"Data sample:\n{data.head()}")
    
    # Create basic info dict
    info = {
        'Filename': input_file,
        'Device': 'ActiGraph GT3X+',
        'ReadErrors': 0,
        'SampleRate': 30,  # After resampling
        'NumTicks': len(data),
        'CalibOK': 1,
        'ReadOK': 1
    }
    
    return data, info

def vectorized_stride_v2(acc, time, window_size, stride_size):
    """Numpy vectorised windowing with stride"""
    start = 0
    max_time = len(time)

    sub_windows = (start +
                   np.expand_dims(np.arange(window_size), 0) +
                   np.expand_dims(np.arange(max_time + 1, step=stride_size), 0).T
                   )[:-1]

    return acc[sub_windows], time[sub_windows]

def df_to_windows(df):
    """Convert a time series dataframe to a windowed Numpy array"""
    acc = df[['x', 'y', 'z']].to_numpy()
    time = df.index.to_numpy()

    # convert to windows
    x, t = vectorized_stride_v2(acc, time, WINDOW_LEN, WINDOW_STEP_LEN)

    # drop the whole window if it contains a NaN
    na = np.isnan(x).any(axis=1).any(axis=1)
    x = x[~na]
    t = t[~na]

    return x, t[:, 0]

def extract_participant_id(filename):
    """Extract participant ID from Strath-Step filename format"""
    # From FLAC_AG_LW_7111_7DRAW.csv extract 7111
    stem = Path(filename).stem
    if 'FLAC_AG_LW_' in stem:
        return stem.split('_')[3]  # Gets 7111 from FLAC_AG_LW_7111_7DRAW
    else:
        return stem.split('_')[0]  # fallback

if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='SSL CSV Inference')
    parser.add_argument('input_file', type=str, help='input CSV file')
    parser.add_argument('--output_dir', type=str, 
                       default='/home/peter.cho@vivosense.com/ssl-ukb/data/strath-step/OxWearables/actiNET',
                       help='output directory')
    args = parser.parse_args()

    start_time = datetime.now()

    input_file = args.input_file
    input_path = Path(input_file)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Extract participant ID
    pt_id = extract_participant_id(input_file)
    
    log.info(f"Processing {input_file}")
    log.info(f"Participant ID: {pt_id}")

    np.random.seed(42)
    torch.manual_seed(42)

    # load config
    cfg = OmegaConf.load("conf/config.yaml")

    GPU = cfg.gpu
    if GPU != -1:
        my_device = "cuda:" + str(GPU)
    else:
        my_device = "cpu"

    # load data
    log.info('Reading CSV data')
    data, info = read_csv_accelerometer(input_file)
    log.info(f"Data shape: {data.shape}")
    log.info(f"Date range: {data.index[0]} to {data.index[-1]}")

    # store original start/end times for reindexing later
    data_start = data.index[0]
    data_end = data.index[-1]

    # prepare dataset
    log.info('Windowing')
    X, T = df_to_windows(data)
    del data  # free up memory

    dataset = NormalDataset(X, name=pt_id)
    dataloader = DataLoader(dataset, batch_size=120, shuffle=False, num_workers=0)

    # load pretrained SSL model
    sslnet = ssl.get_sslnet(my_device, cfg, load_weights=True)

    # load pretrained HMM
    hmm_ssl = HMM(utils.classes, uniform_prior=cfg.hmm.uniform_prior)
    hmm_ssl.load(cfg.hmm.weights_ssl)

    # do inference
    log.info('SSL inference')
    _, y_prob, _ = ssl.predict(sslnet, dataloader, my_device, output_logits=True)
    y_pred = np.argmax(y_prob, axis=1)

    log.info('HMM smoothing')
    y_pred_hmm = hmm_ssl.viterbi(y_pred)

    # construct results dataframe
    df_results = pd.DataFrame({
        'timestamp': T,
        'activity': utils.le.inverse_transform(y_pred_hmm)
    })
    df_results['timestamp'] = pd.to_datetime(df_results['timestamp'])
    df_results.set_index('timestamp', inplace=True)

    # Reindex for missing values
    newindex = pd.date_range(data_start, data_end, freq=f'{WINDOW_SEC}S')
    df_results = df_results.reindex(newindex, method='nearest', fill_value='unknown')

    # Save results
    output_file = output_dir / f"{pt_id}.csv"
    df_results.to_csv(output_file)

    end_time = datetime.now()
    log.info(f'Results saved to {output_file}')
    log.info(f'Duration: {end_time - start_time}')